CREATE TABLE `Escalao` (
  `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `idProva` INT(11) NOT NULL,
  `escalaoNome` varchar(255) NOT NULL, 
  `categoria` varchar(255) NOT NULL, 
  `idadeMin` INT UNSIGNED NULL,	
  `idadeMax` INT UNSIGNED NULL,
  `modified` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP	
);

CREATE TABLE `Ciclista` (
  `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `nome` varchar(255) NOT NULL,
  `dataNascimento` DATE	NOT NULL,
  `dorsal` INT UNSIGNED NULL,
  `modified` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `Participacao` (
  `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `idCiclista` INT(11) NOT NULL,
  `idProva` INT(11) NOT NULL,
  `tempoProva` TIME NULL,
  `escalaoNome` varchar(255) NOT NULL, 
  `modified` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `Prova` (
  `id` INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `ownerID` INT(11) NOT NULL,
  `nome` varchar(255) NOT NULL,
  `dataRealizacao` DATE	NOT NULL,
  `distancia` INT UNSIGNED NULL,
  `modified` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `Utilizadores` (
  `id` INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `username` VARCHAR(256) NOT NULL,
  `email` VARCHAR(256) NOT NULL,
  `password` text NOT NULL,
  `modified` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
